name: rollup-plugin-webbundle CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./rollup-plugin-webbundle

    strategy:
      matrix:
        node-version: [14.x, 16.x]
        rollup-version: [1.21.x, ^1.0.0, ^2.0.0, ^3.0.0]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install rollup@${{ matrix.rollup-version }}
      - run: npm run build --if-present
      - run: npm test
        env:
          CI: true

  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write **/*.{js,ts}
          only_changed: True
          dry: True
          prettier_version: 2.7.1
